version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: denode-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: denode-api
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}


volumes:
  mysql_data:
